config/routes.rb
Rails.application.routes.draw do

  get 'errors/not_found'

  get 'errors/internal_server_error'

  root 'index#index'
  
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  get '/admin', to: 'admin#login'
  post '/admin', to: 'admin#loginPost'
  get '/admin/panel', to: 'admin#panel'
  
  post '/courses/vote', to: 'courses#vote'
  post '/courses/:id', to: 'courses#resetVotes'
  
  resources :locations
  resources :courses
  resources :categories
  resources :users
  
  #if Rails.env.production?
    #get '404', to: 'application#page_not_found'
    #get '422', to: 'application#server_error'
    #get '500', to:  'application#server_error'
  #end
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
  
end

app/views/admin/login.html.erb
<div class="container">
    <h1 class="page-header text-center">Administrator Login</h1>
    <div class="container-decorated decorate-info clearfix">
      <%= form_for(:admin, url: admin_path) do |f| %>
        <div class="field form-group">
          <%= f.label :username %>
          <%= f.text_field :username, class: 'form-control', placeholder: 'Username' %>
        </div>
      
        <div class="field form-group">
          <%= f.label :password %>
          <%= f.password_field :password, class: 'form-control', placeholder: 'Password' %>
        </div>
        
        <div class="actions clearfix">
          <%= link_to 'Back', URI(request.referer || '').path, class:'btn-lg btn btn-link' %>

          <div class="pull-right">
            <%= f.submit 'Login', class: 'btn btn-success btn-lg' %>
          </div>
        </div>
      <% end %>
    </div>
</div>

app/views/admin/panel.html.erb
<div class="container">
    <h1 class="page-header">Administration Panel</h1>
    <p><i>Choose an action:</i></p>
    <ol>
        <li><%= link_to "Manage Users", users_path %></li>
        <li><%= link_to "Manage Courses", courses_path %></li>
        <li><%= link_to "Manage Locations", locations_path %></li>
        <li><%= link_to "Manage Categories", categories_path %></li>
    </ol>
</div>