config/routes.rb
Rails.application.routes.draw do

  get 'errors/not_found'

  get 'errors/internal_server_error'

  root 'index#index'
  
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  get '/admin', to: 'admin#login'
  post '/admin', to: 'admin#loginPost'
  get '/admin/panel', to: 'admin#panel'
  
  post '/courses/vote', to: 'courses#vote'
  post '/courses/:id', to: 'courses#resetVotes'
  
  resources :locations
  resources :courses
  resources :categories
  resources :users
  
  #if Rails.env.production?
    #get '404', to: 'application#page_not_found'
    #get '422', to: 'application#server_error'
    #get '500', to:  'application#server_error'
  #end
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
  
end

app/views/index/index.html.erb
<% provide(:title, "Home") %>
<div class="jumbotron">
    <div class="container text-center">
        <h1>Computer Science Course Manager</h1>
        <%= link_to (fa_icon('user-plus') + ' Sign up now'), signup_path, class: 'btn btn-success btn-lg' %>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-sm-5">
            <h2>View Courses as Guest User</h2>
            <p>
                Browse and view courses as a guest and sign up later.
            </p>
            <%= link_to (fa_icon('book') + ' Browse all courses'), courses_path, class: 'btn btn-info' %>
        </div>
        <div class="col-sm-7">
            <h2>Sign in to your account</h2>
            <p>
                Update your courses, rate courses, view coordinator information.
            </p>
            <%= link_to (fa_icon('sign-in') + ' Log in to your account'), login_path, class: 'btn btn-success' %>
        </div>
    </div>
</div>