config/routes.rb
Rails.application.routes.draw do

  get 'errors/not_found'

  get 'errors/internal_server_error'

  root 'index#index'
  
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  get '/admin', to: 'admin#login'
  post '/admin', to: 'admin#loginPost'
  get '/admin/panel', to: 'admin#panel'
  
  post '/courses/vote', to: 'courses#vote'
  post '/courses/:id', to: 'courses#resetVotes'
  
  resources :locations
  resources :courses
  resources :categories
  resources :users
  
  #if Rails.env.production?
    #get '404', to: 'application#page_not_found'
    #get '422', to: 'application#server_error'
    #get '500', to:  'application#server_error'
  #end
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
  
end

app/views/shared/course_view.html.erb
<div class="container">
  <h1 class="page-header text-center"><%= (@title == nil) ? "All Courses" : @title %></h1>

  <ul class="nav nav-pills" role="tablist">
    <li role="presentation" class="active"><a href="#courses" aria-controls="courses" role="tab" data-toggle="tab">Courses</a></li>
    <li role="presentation"><a href="#coordinators" aria-controls="coordinators" role="tab" data-toggle="tab">Coordinators</a></li>
    <% if(@category != nil && logged_in?) %>
    <li role="presentation" class="pull-right"><%= link_to "Edit Category", edit_category_path(@category), class: "btn-warning" %></li>
    <% elsif(@location != nil && logged_in?) %>
    <li role="presentation" class="pull-right"><%= link_to "Edit Location", edit_location_path(@location), class: "btn-warning" %></li>
    <% end %>
    <% if(logged_in?) %>
    <li role="presentation" class="pull-right"><%= link_to "Add New Course", new_course_path, class: "btn-success" %></li>
    <% end %>
  </ul>
  <hr/>
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="courses">
      <% if @courses.length < 1 %>
        <p>There are no courses to display.</p>
      <% else %>
      <% @courses.each do |course| %>
      <div class="row">
        <div class="col-md-3 text-center" style="padding-top:10px;">
          <% if(course.user != nil) %>
            <%= gravatar_for(course.user, {size: 120, class: 'img-circle'}) %>
            <h5 class="text-uppercase" style="margin-bottom:0px;">Coordinator</h4>
            <p><%= course.user.name %></p>
          <% end %>
          <% if(!current_user.nil? && current_user.admin?) %>
            <%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
          <% end %>
        </div>
        <div class="col-md-9">
          <div class="well">
            <h4><%= link_to course.name, course_path(course) %></h4>
            <p>
              <b>Prerequisite: </b> <%= course.prerequisite %>
            </p>
            <p>
              <b>Category: </b>
                <% course.categories.each do |category| %>
                  <%= link_to category.name, category_path(category), class: 'btn btn-info btn-xs' %>
                <% end %>
            </p>
            <p>
              <b>Location: </b>
                <% course.locations.each do |location| %>
                  <%= link_to location.name, location_path(location), class: 'btn btn-primary btn-xs' %>
                <% end %>
            </p>
            <p>
              <small>Created <%= time_ago_in_words(course.created_at) %> ago</small>
            </p>
            <% if(logged_in?) %>
              <div class="clearfix">
                <div class="pull-right">
                  <%= form_tag(controller: "courses", action: "vote", method: "POST") do %>
                    <%= hidden_field_tag "course_id", course.id %>
                    <%= button_tag(type: "submit", value: "1", name: "vote_type", class: "btn btn-lg btn-link") do %>
                      <span class="glyphicon glyphicon-thumbs-up"></span> <%= course.votes_of_type(1).length %>
                    <% end %>
                    <%= button_tag(type: "submit", value: "0", name: "vote_type", class: "btn btn-lg btn-link") do %>
                      <span class="glyphicon glyphicon-thumbs-down"></span> <%= course.votes_of_type(0).length %>
                    <% end %>
                    <% if !current_user.nil? && current_user.admin? %>
                      <%= link_to 'Reset', course, method: :resetVotes, data: { confirm: 'Are you sure?' }, class: "btn btn-info btn-xs" %>
                    <% end %>
                  <% end %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
      <% end %>
      <% end %>
    </div>
    <div role="tabpanel" class="tab-pane" id="coordinators">
      <% if (@courses.pluck(:created_by).uniq.length < 1) %>
        <p>There are no coordinators to display.</p>
      <% else %>
        <% @courses.pluck(:created_by).uniq.each do |coordinator| %>
            <% @user = User.where(["id = :id", {:id => coordinator}]).first %>
            <div class="block text-center">
                <%= gravatar_for(@user, {size: 240, class: 'img-circle'}) %>
                <h4 class="text-uppercase" style="margin-bottom:0px;">Coordinator</h4>
                <h2 style="margin-top:0px;"><%= @user.name %></h2>
            </div>
            <hr/>
        <% end %>
      <% end %>
    </div>
  </div>
</div>