config/routes.rb
Rails.application.routes.draw do

  get 'errors/not_found'

  get 'errors/internal_server_error'

  root 'index#index'
  
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  get '/admin', to: 'admin#login'
  post '/admin', to: 'admin#loginPost'
  get '/admin/panel', to: 'admin#panel'
  
  post '/courses/vote', to: 'courses#vote'
  post '/courses/:id', to: 'courses#resetVotes'
  
  resources :locations
  resources :courses
  resources :categories
  resources :users
  
  #if Rails.env.production?
    #get '404', to: 'application#page_not_found'
    #get '422', to: 'application#server_error'
    #get '500', to:  'application#server_error'
  #end
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
  
end

app/views/layouts/_footer.html.erb
<footer>
    <div class="container">
        <h3>Contact Us</h3>
        <%= link_to "admin@sciencecourses.rmit.edu.au", "mailto:admin@sciencecourses.rmit.edu.au" %>
    </div>
</footer>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#nav-links" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'CSMS', root_path, class: 'navbar-brand' %>
    </div>

    <div class="collapse navbar-collapse" id="nav-links">
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Category <span class="caret"></span></a>
          <ul class="dropdown-menu">
             <% @categories.each do |category| %>
               <li><%= link_to category.name, category %></li>
             <% end %>
             <%= '<li class="unavailable"><a class="text-uppercase"><b>No Categories</b></a></li>'.html_safe if (@categories.count == 0) %>
             <% if logged_in? %>
               <li role="separator" class="divider"></li>
               <li><%= link_to 'New Category', new_category_path %></li>
             <% end %>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Locations <span class="caret"></span></a>
          <ul class="dropdown-menu">
             <% @locations.each do |location| %>
               <li><%= link_to location.name, location %></li>
             <% end %>
             <%= '<li class="unavailable"><a class="text-uppercase"><b>No Locations</b></a></li>'.html_safe if (@locations.count == 0) %>
             <% if logged_in? %>
                <li role="separator" class="divider"></li>
               <li><%= link_to 'New Location', new_location_path %></li>
             <% end %>
          </ul>
        </li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user[:name] %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <% if current_user.admin %>
               <li><%= link_to "Administration Panel", admin_panel_path %></li>
              <% end %>
               <li><%= link_to "View Profile", user_path(current_user) %></li>
               <% if !current_user.admin? %>
               <li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
               <% end %>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Log out", logout_path, method: "delete" %></li>
            </ul>
          </li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Login <span class="caret"></span></a>
            <ul class="dropdown-menu">
                <li><%= link_to 'Coordinator', login_path %></li>
                <li><%= link_to 'Administrator', admin_path %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Roboto:400,400i,500,500i,700,700i' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    
    <% flash.each do |message_type, message| %>
      <div class="container">
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      </div>
    <% end %>

    <%= yield %>
    
    <%= render 'layouts/footer' %>
  </body>
</html>